spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.100.101:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: on
server:
  port: 12000